id: I48F47906
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:05:47+00:00'
last_modified: '2022-06-08T02:39:39.901657+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30480
  title: ཆུ་མོ་ལི་ཁྲིའི་ནོར་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4B06:
      image_group_id: I1KG16927
      title: ''
      total_pages: 588
      order: 1
      base_file: 4B06.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
